### ISSUE TITLE
Incorrect output blueprint

### ISSUE THREAD

**Issue by vandervecken** [kevL/TccScripts#10]
An incorrect output blueprint (should be nw_wammbo001 instead of nw_wammbo002):

![0d9ed750d19aa833fca29c9cdfae3ea13ffb437f_1_690x410](https://user-images.githubusercontent.com/4950318/46713467-a59c7180-cc0b-11e8-8e10-faaf9828b5de.jpeg)

**Comment by Aqvilinus** [comment]
Spell ID #1031 is Hypothermia.
Bolts: Frostbite = Mithral + Bolt Mold + Ray of Frost/Hypothermia (Level 10)

It produces Lightning bolts (nw_wammbo002) instead of Frostbite ones (nw_wammbo001).
