### ISSUE TITLE
Ammo template issues

### ISSUE THREAD

**Issue by vandervecken** [kevL/TccScripts#12]
Missing templates (they have masterwork versions *_mast, but don’t have the ordinary ones):

    tcc_arrow_cld_001
    tcc_arrow_slv_001
    tcc_bolt_cld_001
    tcc_bolt_slv_001
    tcc_bullet_cld_001
    tcc_bullet_slv_001
    tcc_ring_001
    tcc_ring_ada_001

This one doesn’t have a masterwork version:

    nw_wbwsl001_mast

All new ammo templates use incorrect icons. There’re appropriate icons for adamantine, silver, mithril arrows, bolts, bullets in the stock game. Just use them.

**Comment by Aqvilinus** [comment]
This one doesn't require renumbering crafting.2da.

**Comment by vandervecken** [comment]
as far as I recall, the result of whether you get masterwork or non-masterwork is based on your skill value versus the threshold requirement. I think we made Masterwork require +5 skill.
So what happens if you don't have that skill, the recipe fails for lack of a non-masterwork template?

**Comment by Aqvilinus** [comment]
>the recipe fails for lack of a non-masterwork template?
Exactly, Look at ``CreateListOfItemsInInventory()``:

```
// Creates the items of sResrefList in the inventory of oContainer.
// - bIdentify : -1 leave default
//				  0 set not identified
//				  1 set identified
void CreateListOfItemsInInventory(string sResrefList,
								  object oContainer = OBJECT_SELF,
								  int bIdentify = TRUE,
								  int bMasterwork = FALSE,
								  int bFullStack = FALSE)
{
	//TellCraft("CreateListOfItemsInInventory() ( " + sResrefList + " )");
	object oCreate;

	string sResrefMstrwork;

	int i = 0;
	string sResref = GetStringParam(sResrefList, i);
	while (sResref != "")
	{
		//TellCraft(". resref= " + sResref);
		oCreate = OBJECT_INVALID;

		if (bMasterwork)
		{
			sResrefMstrwork = sResref + TCC_MASTER_TAG;
			oCreate = CreateItemOnObject(sResrefMstrwork, oContainer);
			TellCraft(". . masterwork ! ( " + sResrefMstrwork + " )" + (!GetIsObjectValid(oCreate) ? " WARNING : no masterwork resref" : ""));
		}

		if (!GetIsObjectValid(oCreate))
		{
			//TellCraft(". creating : " + sResref);
			oCreate = CreateItemOnObject(sResref, oContainer);
		}

		if (GetIsObjectValid(oCreate))
		{
			if (bMasterwork) // set Masterwork flag whether or not item was created w/ a Masterwork-resref.
				SetLocalInt(oCreate, TCC_VAR_MASTERWORK, TRUE);

			if (bIdentify != -1)
				SetIdentified(oCreate, bIdentify);

			if (bFullStack)
				SetItemStackSize(oCreate,
								 StringToInt(Get2DAString("baseitems", "Stacking", GetBaseItemType(oCreate))));
		}
		//else TellCraft(". . ERROR : failed to create ( " + sResref + " )");

		sResref = GetStringParam(sResrefList, ++i);
	}
}
```

**Comment by Aqvilinus** [comment]
Maybe use generic icons for both iron and darksteel ammunition?

**Arrows:**
Adamantium - it_wo_arrowadam
Cold Iron - it_wo_arrowiron
Darksteel - it_wo_arrow00 (generic iron)
Iron - it_wo_arrow00 (generic iron)
Mithral - it_wo_arrow02
Silver - it_wo_arrowsilver

**Bolts:**
Adamantium - it_wo_boltadam
Cold Iron - it_wo_bolt01
Darksteel - it_wo_bolt00 (generic iron)
Iron - it_wo_bolt00 (generic iron)
Mithral - it_wo_bolt02
Silver - it_wo_boltsilver

**Bullets:**
Adamantium - it_wo_bulletadam
Cold Iron - it_wo_bulletiron
Darksteel - it_wo_bullet00 (generic iron)
Iron - it_wo_bullet00 (generic iron)
Mithral - it_wo_bullet02
Silver - it_wo_bulletsilver

**Shurikens:**
Adamantium - it_wt_shurikenadam
Cold Iron - it_wt_shurikeniron
Darksteel - it_wt_shuriken00 (generic iron)
Iron - it_wt_shuriken00 (generic iron)
Mithral - it_wt_shuriken02
Silver - it_wt_shurikensilver

**Darts:**
Adamantium - it_wt_dartadam
Cold Iron - it_wt_dartiron
Darksteel - it_wo_dart00 (generic iron)
Iron - it_wo_dart00 (generic iron)
Mithral - it_wo_dart02
Silver - it_wt_dartsilver

**Throwing Axes:**
Adamantium - it_wt_taxeadam
Cold Iron - it_wt_taxeiron
Darksteel - it_wt_taxe00 (generic iron)
Iron - it_wt_taxe00 (generic iron)
Mithral - it_wt_taxe02
Silver - it_wt_taxesilver

**Comment by vandervecken** [comment]
This makes sense to me. Working on it.
