### ISSUE TITLE
MotB recipe for Staff of Ashenwood

### ISSUE THREAD

**Issue by kevL** [kevL/TccScripts#21]
id: 1188
reagents: nx1_cft_ess_woodman,nx1_crft_charred_branch
category: 1111 - SPELLABILITY_MOLD_SPIRIT
output: nx1_staff01
skill: 2050 - FEAT_MALLEATE_SPIRIT

Issue: It looks like all the other MotB recipes mate the trigger SPELLABILITY_MOLD_SPIRIT with FEAT_MOLD_SPIRIT, and SPELLABILITY_MALLEATE_SPIRIT with FEAT_MALLEATE_SPIRIT, but this one crosses Mold/Malleate.

**Comment by Aqvilinus** [comment]
Yeah, it definitely looks like a bug. 

SPELLABILITY_MOLD_SPIRIT (1111) -> SPELLABILITY_MALLEATE_SPIRIT (1112).
