### ISSUE TITLE
id 990

### ISSUE THREAD

**Issue by kevL** [kevL/TccScripts#22]
![yata_id990](https://user-images.githubusercontent.com/5395276/47055576-42638f80-d175-11e8-98d1-f12c58ca5baa.png)

no EFFECTS, no OUTPUT ... delete?

trigger is Identify -- is something to do with PropertySets maybe?

<br>
Also bad REAGENT order : "air2" should come before "earth3"

**Comment by vandervecken** [comment]
There is a missing recipe here: Spell Focus (Transmutation). The problem is that IPRP_Feats.2da does not provide Spell Focus Transmutation, even though it is present in Feats.2da.

Thoughts?
Should we ship a replacement iprp_feats.2da? Or just leave it?

**Comment by vandervecken** [comment]
Can we just use the one in NWN2Fixes, or would we need to include additional code from NWN2Fixes if we did so? I would hate to generate incompatibility with that mod.

**Comment by kevL** [comment]
yep, use the one from Nwn2fixes. It's good to go
