### ISSUE TITLE
acid unlimited ammo

### ISSUE THREAD

**Issue by zzcmeiou** [kevL/TccScripts#34]
iprp_ammocost 2da

16	1632	1d6Acid	4	NW_WAMMAR003	NW_WAMMBO099	X2_WAMMBU099

The bullet blueprint is wrong, X2_WAMMBU099 does not exist

Should be N2_WAMMBU099

**Comment by kevL** [comment]
Nw_WAMMBU099, i think

**Comment by vandervecken** [comment]
Thanks. Nice to know someone else is paying careful attention!
