### ISSUE TITLE
wrong vfx?

### ISSUE THREAD

**Issue by zzcmeiou** [kevL/TccScripts#37]
Melee acid weapon enchant showing wrong visual effect on weapon and on hit - showing sonic visuals instead of acid weapon drips and acid splash on hit. However the enchant works correctly, dealing acid damage.

closed;

weapon had pre existing damge bonus to evil effect.

**Comment by zzcmeiou** [comment]
Forgot items retain the 1st visual effect and do not apply subsequent visual effects.

**Comment by vandervecken** [comment]
Still appreciate the attention though.
