### ISSUE TITLE
Unlimited ammo overwrite

### ISSUE THREAD

**Issue by zzcmeiou** [kevL/TccScripts#38]
Is it possible to overwrite unlimited ammo on a ranged weapon?

Currently it stacks;

weapon has unlimited ammo +3
enchant unlimited ammo +5
weapon now has both, but uses the latest property.

I think this is a waste of item slots.....

===========

any way to remove enchants[make a slot empty again], apart from cheating by increasing the available slots in config file?

**Comment by kevL** [comment]
interesting ... there are some types of enchantments that check for and clear prior props when they're redundant. i'd think UnlimitedAmmo should be one of them,

**Comment by zzcmeiou** [comment]
![nwn06](https://user-images.githubusercontent.com/15532166/47715227-1585a100-dc7a-11e8-9f96-1f7f8846f3f2.jpg)


This is what I mean.

The fire ammo was 1st.
Then the cold ammo.

It now uses the cold ammo, therefore the fire ammo is eating up a slot.

Somehow the check script is not working. 

Or it could be due to the property type;
You can also put multiple class, race, alignment limitations on items.

Like Lawful Chaotic Human Elf Wizard Rogue. Possible by upping the slot count. although there are items that have 2 classes, or 2 alignments limitation.

If these were allowed to overwrite; you cannot put the above combination on an item.

============

I should make it clearer; any way to clear an item slot/remove enchant? Like using a spell to clear out a slot.

**Comment by kevL** [comment]
remove those by custom script

but it also points out an issue in Reboot that ought be addressed ...

**Comment by vandervecken** [comment]
I agree that each Unlimited Ammo recipe should overwrite all Unlimited ammo recipes. That should be something you can do in ginc_crafting as a special case?

As for removing an enchantment. I don't see how you would do it with a recipe. How would the recipe determine which slot to delete> They aren't in order.

You could write a custom script, but then if the user is already cheating they can just recreate the item from scratch.

**Comment by kevL** [comment]
> I agree that each Unlimited Ammo recipe should overwrite all Unlimited ammo recipes. That should be something you can do in ginc_crafting as a special case?

yep (it's prioritized on my TODO)

> As for removing an enchantment. I don't see how you would do it with a recipe. How would the recipe determine which slot to delete? They aren't in order.

it'd require a fair bit of recipe+code insertion ... not a priority imo.

**Comment by zzcmeiou** [comment]
I was also doing my own thinking after bringing up the remove enchant, and well yeah it would be a fair bit of work.

**Comment by kevL** [comment]
https://github.com/kevL/TccScripts/commit/79269f8af2fa37ea73dd1898d0b9b35dd8c69b86
