### ISSUE TITLE
Acid unlimited ammo

### ISSUE THREAD

**Issue by zzcmeiou** [kevL/TccScripts#39]
I think it needs more work.

![nwn07](https://user-images.githubusercontent.com/15532166/47727396-4fb16b80-dc97-11e8-8b44-ba8ccf7d77cc.jpg)

The AI char is NOT using the weapon. It acts as if the ammo has run out. A controlled char is able to use the weapon normally.

I'm still testing other combinations.

**Comment by kevL** [comment]
... this isn't a Reboot issue

it's a general AI issue and there's, uh, a few things the AI doesn't do right

**Comment by zzcmeiou** [comment]
Alright, I think I found the cause.

I have Tony AI mod.

Prolonged combat;
I was using NESS persistent spawn, and let it run for an hour or 2. Then I noticed this odd occurrence.

The weapon is unequipped, but the ammo is left behind. This causes the AI to believe the weapon is out of ammo. Re equipping the weapon does not fix it.

Reloading the game cleaned it off.

Probly close this as AI bug.

**Comment by kevL** [comment]
k
