### ISSUE TITLE
Missing bonus hp recipes?

### ISSUE THREAD

**Issue by zzcmeiou** [kevL/TccScripts#40]
680 137 nx1_cft_ess_earth02 2 66,6,0,0,0 **** 1092 12 **** 0 0 0
681 137 nx1_cft_ess_earth02,nx1_cft_ess_earth02 2 66,9,0,0,0 **** 1092 15 **** 0 0 0
682 137 nx1_cft_ess_earth02,nx1_cft_ess_earth02,nx1_cft_ess_earth02 2 66,12,0,0,0 **** 1092 18 **** 0 0 0
683 137 nx1_cft_ess_earth02,nx1_cft_ess_earth02,nx1_cft_ess_earth02,nx1_cft_ess_earth02 2 66,15,0,0,0 **** 1092 21 **** 0 0 0
684 137 nx1_cft_ess_earth03 2 66,18,0,0,0 **** 1092 24 **** 0 0 0
685 137 nx1_cft_ess_earth03,nx1_cft_ess_earth03 2 66,21,0,0,0 **** 1092 27 **** 0 0 0
686 137 nx1_cft_ess_earth03,nx1_cft_ess_earth03,nx1_cft_ess_earth03 2 66,23,0,0,0 **** 1092 30 **** 0 0 0

As far as I can see these are;
bonus hp recipes, 
using protection from energy spell, 
enchant any armor & shield,  
not disabled,
using different grades and quantities of earth essences.

No mention of any bonus hp recipe in the readme. Is this deliberate?

**Comment by vandervecken** [comment]
The giveaway is that they use nx1_cft_ess - they are recipes from Mask of the Betrayer (which is nx1 - expansion 1).
We pretty much leave the MotB recipes alone. You can find them in the MotB recipe guides.

**Comment by zzcmeiou** [comment]
Ah I forgot the significance of the prefix nx1.
