### ISSUE TITLE
Other damage types?

### ISSUE THREAD

**Issue by zzcmeiou** [kevL/TccScripts#41]
Damage types not available via enchanting;

Subdual - other games use this type to stun/subdue target, probly redundant with stun on hit property.
Positive - am not sure what benefit does this have.
Negative -  am not sure what benefit does this have.
Divine - Bonus on outsider or undead?
Magical? This is used for spells, and some special traps.
Physical?

Any plans to enable? Just curious.

**Comment by kevL** [comment]
subdual and physical are obsolete. They shouldn't be used

the others may need testing based on exactly what itemproperties they're being assigned to ... the docs are a bit fuzzy/puzzling

**Comment by vandervecken** [comment]
No particular plans to expand the recipe pool, no.

**Comment by vandervecken** [comment]
Though if you can think of a compelling reason, I'm all ears.
