### ISSUE TITLE
Crafting elemental arrows has inconsistent requirements

### ISSUE THREAD

**Issue by vandervecken** [kevL/TccScripts#42]
For some reason Lightning arrows require skill 17 while other arrows - ice, acid and fire require skill 12. Which way to rebalance?
I think that seeing as skill 17 corresponds to Level 10 (with Int 18), they should all go up to 17.

From here: https://forum.neverwintervault.org/t/the-issue-of-archery/1312/14

**Comment by kevL** [comment]
L10 sounds reasonable -- could split the difference at skill ~15?
