### ISSUE TITLE
add Sonic damage UnlimitedAmmo (on ranged weapons)

### ISSUE THREAD

**Issue by kevL** [kevL/TccScripts#43]
i happened to glance at Iprp_AmmoCost.2da and saw the new Acid-type ... looked up and saw the other elemental types ... <s>sonic needs a hug</s>

**Comment by vandervecken** [comment]
is this necessary? There aren't any such things as sonic arrows are there?

**Comment by kevL** [comment]
not necessary, just a possible feature. I suppose the blueprints would need to be created ...

**Comment by zzcmeiou** [comment]
Actually there is one unlimited sonic ammo - the reverberating shot;

**Reverberating Crossbow of Pain**
Base Damage: 1d8
Base Critical Threat: 19-20/x2
Base Damage Type: Piercing
Weapon Size: Small
Feats Required: Simple, Monk, Rogue, or Wizard
Base Item: Light Crossbow
Weight: 4 pound(s)
Resource Name: nx1_lightcrossbow01
Installation: Mask of the Betrayer

**Special Properties**
Attack Bonus [+ 6]
Decreased Attack Modifier [-5]
**Unlimited Ammunition: Bolt [Ammo: Reverberating Shot]**  the blueprint covers all 3 ammo types, has 6 piercing dmg, sonic 4d6 dmg

**Comment by vandervecken** [comment]
I don't think this should be a generic ammo type though. It's nice that the Crossbow of pain exists, but I don't think that a Sonic Arrow needs to exist in TCC. Mostly for balance reasons. Sonic is generally a far superior damage type because fewer things have resistance to it.

**Comment by kevL** [comment]
k

**Comment by kevL** [comment]
ps. level req'd could be upped
