### ISSUE TITLE
Saving throws save element.

### ISSUE THREAD

**Issue by zzcmeiou** [kevL/TccScripts#47]
There is only 1 savelement 2da;

2DA V2.0                                  
                                          
           Name   NameString       Cost   
0          5152   Universal        1.25   
1          1027   Acid             0.4    
2          ****   Backstab         0.4    
3          1029   Cold             0.4    
4          5154   Death            0.75   
5          1006   Disease          0.5    
6          5155   Divine           0.4    
7          1030   Electrical       0.4    
8          993    Fear             0.4    
9          1028   Fire             0.5    
10         ****   Illusion         0.5    
11         5157   Mind-Affecting   0.75   
12         5158   Negative         0.75   
13         879    Poison           0.5    
14         5159   Positive         0.4    
15         2202   Sonic            0.4    
16         ****   Traps            0.4    
17         ****   Spells           0.75   
18         ****   Law              0.4    
19         ****   Chaos            0.4    
20         ****   Good             0.4    
21         ****   Evil             0.4    

**0          5152   Universal        1.25**   This one strangely gives a bonus to fort,reflex,will, up to 12 each. Has no effect if value is greater than 12.

By convention universal should mean save vs all the elements listed in the 2da.

Another odd thing, putting this property on 2 different items, assume the max value of 12, yields a bonus 12 + 5 instead of 12 +12. 

This is really befuddling me. How did all this strange bugs come about....

**Comment by zzcmeiou** [comment]
Save element also needs to be changed to refer bonuscost. Thats the main thing.

What I dont understand is the universal property.

Is it really meant to also include saving throw?? I think it should be just provide bonus to all the elements in the 2da list. Including elements that are outside seems rather odd.

**Comment by vandervecken** [comment]
> Save element also needs to be changed to refer bonuscost. Thats the main thing.
Why? What would this accomplish? We don't know what kinds of possible effects such a change would have, and it doesn't seem to solve any real problem. Why beg trouble?

As for the Universal property, again I don't see how there's anything to be gained here. What kind of functionality are we attempting to enable? What kind of buggy behaviour are users experiencing?

This all seems like making problems for ourselves really, and I see very little to gain.

**Comment by vandervecken** [comment]
Remember, our job here isn't code quality and making things fit some sort of design aesthetic. Our goal here is to implement user-facing functionality. This doesn't seem to have any user-facing benefit, nor does it help make the modding easier.

**Comment by zzcmeiou** [comment]
I guess I got too over excited. But I think this does explain why the [all] property in saving throws 2da does not work. Somehow its function is in this property.

**Comment by vandervecken** [comment]
Some more detail here:
@kevL and I discovered that the "All" value in iprp_savingthrow doesn't work. Fort/Ref/Will all work, but "All" doesn't. Could never figure out why. Which is why we currently have the bonus-to-all-saves set to the Universal value in iprp_saveelement.

I don't know why All doesn't work, and I don't know what we would do differently with Universal even if it did, so best to let sleeping dogs lie?

**Comment by kevL** [comment]
yep.

cf, https://github.com/kevL/TccScripts/issues/5 - the two savebonus things seem to have hardcoded borks, so ... yeh

feel free to close imo.
