### ISSUE TITLE
identical trap recipes

### ISSUE THREAD

**Issue by kevL** [kevL/TccScripts#48]
these two (identical) recipes appear to output different trapkits (unless I'm missing something)

ids
1591
1611

![identical_trap_recipes](https://user-images.githubusercontent.com/5395276/48302147-ccbdbb80-e4b5-11e8-9381-d44a892297a1.png)

assume the first that the code finds is the one that gets created ...

There are others also, like 1594/1614 and 1592/1612

**Comment by vandervecken** [comment]
Acid Blob traps are broken, will fix.

**Comment by kevL** [comment]
idk Lol. Traps are a specialized subsystem in themselves

**Comment by vandervecken** [comment]
Fixed.
