### ISSUE TITLE
Lucky is not working?

### ISSUE THREAD

**Issue by vandervecken** [kevL/TccScripts#5]
Aqvilinus says:
    Lucky: Adds +1 to all saves
    Requires: Caster Level 5, Craft Magic Arms and Armor feat
    Ingredients: Faint Power Essence + Faint Earth Essence + Obsidian
    Spell: Resistance

encoded incorrectly as “40,1,3,0,0” (bonus +3 to Fortitude saves). Should be “40,0,1,0,0”.

**Comment by vandervecken** [comment]
Pushed this change for testing:
https://github.com/kevL/TccScripts/tree/test_lucky

**Comment by kevL** [comment]
dang, doesn't work - sry bout that.

will make more comments about it on the commit page

**Comment by vandervecken** [comment]
After doing some testing we decided to delete this recipe, which will be a heavy diff since it involves renumbering crafting.2da.

**Comment by kevL** [comment]
odd ...

ItemPropDef.2da #40 ITEM_PROPERTY_SAVING_THROW_BONUS

says use Iprp_SaveElement.2da for subtypes

but that 2da doesn't mention fort/will/refl. Instead it has a bunch of elements, plus stuff like Backstab and Mind-affecting.

So it looks like ItemPropertyBonusSavingThrow() is overruling its 2da-subtype behind the scenes, using the IP_CONST_SAVEBASETYPE_* values directly for fort/will/refl, but it was never fully implemented and debugged.

Note also that the next ip in ItemPropDef.2da #41 ITEM_PROPERTY_SAVING_THROW_BONUS_SPECIFIC

says use Iprp_SavingThrow.2da for subtypes

and *that* 2da has fort/will/refl ... but ItemPropertyBonusSavingThrowVsX() again looks like it bypasses its 2da-subtype and uses the IP_CONST_SAVEVS_* values directly.

https://www.youtube.com/watch?v=z02J_kPincA

**Comment by vandervecken** [comment]
I'm well aware that there are two different IPRP tables for saves. It's quite possible that we may be able to get Lucky to work by using the "Universal" in SaveElement instead of the All in SavingThrow.

**Comment by kevL** [comment]
```c++
int IP_CONST_SAVEVS_UNIVERSAL = 0;
int IP_CONST_SAVEBASETYPE_ALL = 0;
```
they're both (int)0 ... both as constants and in the 2das -- changing them won't make any difference to the function

**Comment by Aqvilinus** [comment]
@vandervecken probably means using #41 ITEM_PROPERTY_SAVING_THROW_BONUS_SPECIFIC with IP_CONST_SAVEVS_UNIVERSAL. But I'm not sure whether it would be equivalent to #40 is ITEM_PROPERTY_SAVING_THROW_BONUS with IP_CONST_SAVEBASETYPE_ALL.

**Comment by Aqvilinus** [comment]
@vandervecken probably means using #41 ITEM_PROPERTY_SAVING_THROW_BONUS_SPECIFIC with IP_CONST_SAVEVS_UNIVERSAL. But I'm not sure whether it would be equivalent to #40 ITEM_PROPERTY_SAVING_THROW_BONUS with IP_CONST_SAVEBASETYPE_ALL. Anyway, it's better than nothing.

**Comment by vandervecken** [comment]
FYI they're actually under Misc, not Feats.
https://github.com/kevL/TccScripts/blob/master/Rebalanced%20Crafting%20Recipes.txt#L2207

**Comment by vandervecken** [comment]
That said, Lucky isn't ever going to work properly, for two reasons:
1) The way Lucky is implemented in defined items like the Luckstone is with over a dozen individual +1 properties
2) The whole point of Luck bonuses has always been that they are supposed to stack with non-luck bonuses. However I don;t think NWN2 has a concept of bonus types here. "luck bonus vs morale bonus vs enhancement bonus" which means Luck bonus to saves is the same as Resistance bonus to saves.

**Comment by vandervecken** [comment]
@kevL for your most recent comment here - could you clarify where in the code you're looking at? It's not in the mod - somewhere in the base game?

**Comment by kevL** [comment]
yep the stuff i mentioned is in nwscript.nss -- the core interface with the engine for all scripting.

if you want to keep a copy of nwscript.nss loose on your hardrive for reference, find the most recent in

C:\Neverwinter Nights 2\Data\scripts_X2.zip\Scripts_X2\nwscript.nss

(or thereabouts)

**Comment by vandervecken** [comment]
I just looked up the Rebalanced Crafting Recipes.txt in the NWN Vault, and on line 2207 there's "*** Misc ***"

Anyway, I reckon for the reasons I listed above that this will likely never work the way it's intended.
