### ISSUE TITLE
Bug with blueprints for adamantine shields

### ISSUE THREAD

**Issue by Aqvilinus** [kevL/TccScripts#51]
> Due to a bug, Adamantine shields confer no damage reduction. This is because all Adamatine shields list damage reduction as “DR x/” (without the hyphen) instead of “DR x/-”. The result is these shields are missing the type of damage to which they have a reduction and, therefore, no DR effect, because everything penetrates.

http://nwn2.wikia.com/wiki/Adamantine

**Comment by vandervecken** [comment]
@Aqvilinus and @kevL I have committed a new Heavy Adamantine Shield that *appears* to have the "-" in it.
Please test it in combat? If it's good I'll add the rest as Template Overrides. This might be eligible for the nwn2fixes mod as well?

**Comment by kevL** [comment]
it's been a heavy day for me, not sure i'll get to have a closer look/ test it before tomorrow,

**Comment by vandervecken** [comment]
It does work! I'm going to submit these to nwn2fixes.

**Comment by vandervecken** [comment]
@kevL  one last question for you here:
https://github.com/kevL/TccScripts/pull/53
Then I think I'm ready to put the final documentation touches on a release.

**Comment by vandervecken** [comment]
Fixed with https://github.com/kevL/TccScripts/pull/53
