### ISSUE TITLE
Masterwork Adamantine Heavy Shield is accidentally Cursed

### ISSUE THREAD

**Issue by vandervecken** [kevL/TccScripts#58]
Looks like /Templates/mwa_shhv_ada_4_mast.UTI has its Cursed flag set

**Comment by vandervecken** [comment]
@kevL do you currently have NWN2 installed? This should be trivial to fix. If not, I can do it.

**Comment by kevL** [comment]
https://github.com/kevL/TccScripts/commit/5bda28d8fa5a5d1e62fa8d1e4e4241243de7d169

that should do it for the repo -- just do your voodoo for the Vault package :)
